import { jsPDF } from 'jspdf'
import { CATEGORIES } from '../data/categories'
import { STUDY_TIPS } from '../data/studyTips'
import type { Language } from '../i18n'
import type { CategoryId, Result, Team } from './types'

const MEDALS: Record<Language, string[]> = {
  en: ['1st', '2nd', '3rd', '4th'],
  pt: ['1o', '2o', '3o', '4o'],
}

const STRINGS = {
  en: {
    title: '# CCA-F Hunt — Performance Report',
    generatedOn: 'Generated on: ',
    ranking: '## Ranking',
    finalScore: 'Final score',
    questionsAnswered: 'Questions answered',
    correct: 'correct',
    wrong: 'wrong',
    noAnswers: '_This team did not answer any question._',
    byDomain: '### Performance by domain',
    correctSuffix: 'correct',
    wrongQuestions: '### Wrong questions',
    noneWrong: '_None! You got every question you answered right._',
    whatToStudy: '### What to study further',
    greatJob:
      'Great job! Reinforce by reviewing the highest-weight domains on the exam to consolidate.',
    prioritize:
      'Based on your mistakes, prioritize these domains (ordered by exam weight):',
    claudePromptTitle: '### Prompt to paste into Claude',
    claudePromptIntro:
      'Paste the text below into a conversation with Claude to get help focused on your mistakes:',
    footer:
      '_Report generated by CCA-F Hunt performance analysis (local rules, no online AI)._',
  },
  pt: {
    title: '# CCA-F Hunt — Relatório de Desempenho',
    generatedOn: 'Gerado em: ',
    ranking: '## Ranking',
    finalScore: 'Pontuação final',
    questionsAnswered: 'Perguntas respondidas',
    correct: 'acertos',
    wrong: 'erros',
    noAnswers: '_Este time não respondeu nenhuma pergunta._',
    byDomain: '### Desempenho por domínio',
    correctSuffix: 'acertos',
    wrongQuestions: '### Perguntas erradas',
    noneWrong: '_Nenhuma! Acertou todas as perguntas que respondeu._',
    whatToStudy: '### O que aprofundar nos estudos',
    greatJob:
      'Ótimo desempenho! Reforce revisando os domínios de maior peso na prova para consolidar.',
    prioritize:
      'Com base nos seus erros, priorize estes domínios (ordenados pelo peso na prova):',
    claudePromptTitle: '### Prompt para colar no Claude',
    claudePromptIntro:
      'Cole o texto abaixo numa conversa com o Claude para receber ajuda focada nas suas falhas:',
    footer:
      '_Relatório gerado por análise de desempenho do CCA-F Hunt (regras locais, sem IA online)._',
  },
}

const CLAUDE_PROMPT = {
  en: {
    copyFrom: '--- COPY FROM HERE ---',
    intro:
      "I'm studying for the Claude Certified Architect (CCA-F) certification and used a quiz to practice.",
    allCorrect:
      'I got every question I answered right. Propose harder scenario questions in the highest-weight exam domains (Agentic/Research, Extraction, Support and Code) and explain the reasoning behind each correct answer.',
    upToHere: '--- UP TO HERE ---',
    gotWrong:
      "I got the questions below wrong. For each one: explain the concept behind it, why the correct option is the best, what the traps are, and where I probably got confused. At the end, build a study plan focused on my weak domains.",
    weakDomains: 'Domains with most mistakes: ',
    wrongList: 'Questions I got wrong:',
  },
  pt: {
    copyFrom: '--- COPIE DAQUI ---',
    intro:
      'Estou estudando para a certificação Claude Certified Architect (CCA-F) e usei um quiz para praticar.',
    allCorrect:
      'Acertei todas as perguntas que respondi. Me proponha questões mais difíceis, em formato de cenário, nos domínios de maior peso da prova (Agentic/Research, Extraction, Support e Code) e explique o raciocínio de cada resposta correta.',
    upToHere: '--- ATÉ AQUI ---',
    gotWrong:
      'Errei as questões abaixo. Para cada uma: explique o conceito por trás, por que a alternativa correta é a melhor, quais são as pegadinhas, e onde eu provavelmente me confundi. No final, monte um plano de estudo focado nos meus domínios fracos.',
    weakDomains: 'Domínios com mais erros: ',
    wrongList: 'Perguntas que errei:',
  },
}

interface DomainSummary {
  category: CategoryId
  name: string
  weight: number
  total: number
  correct: number
}

function summarizeDomains(teamHistory: Result[]): DomainSummary[] {
  return CATEGORIES.map((cat) => {
    const inDomain = teamHistory.filter((r) => r.category === cat.id)
    return {
      category: cat.id,
      name: cat.name,
      weight: cat.weight,
      total: inDomain.length,
      correct: inDomain.filter((r) => r.answeredCorrectly).length,
    }
  })
}

function buildClaudePrompt(teamHistory: Result[], language: Language): string[] {
  const s = CLAUDE_PROMPT[language]
  const lines: string[] = []
  const wrong = teamHistory.filter((r) => !r.answeredCorrectly)
  const weak = summarizeDomains(teamHistory)
    .filter((d) => d.total > 0 && d.correct < d.total)
    .sort((a, b) => b.weight - a.weight)
    .map((d) => d.name)

  lines.push(s.copyFrom)
  lines.push('')
  lines.push(s.intro)

  if (wrong.length === 0) {
    lines.push(s.allCorrect)
    lines.push('')
    lines.push(s.upToHere)
    return lines
  }

  lines.push(s.gotWrong)
  lines.push('')
  if (weak.length > 0) {
    lines.push(`${s.weakDomains}${weak.join(', ')}.`)
    lines.push('')
  }
  lines.push(s.wrongList)
  wrong.forEach((r, i) => {
    lines.push(`${i + 1}. [${r.categoryName}] ${r.prompt}`)
  })
  lines.push('')
  lines.push(s.upToHere)
  return lines
}

export function generateReport(
  teams: Team[],
  history: Result[],
  language: Language,
): string {
  const s = STRINGS[language]
  const medals = MEDALS[language]
  const ranking = [...teams].sort((a, b) => b.points - a.points)
  const locale = language === 'pt' ? 'pt-BR' : 'en-US'
  const lines: string[] = []

  lines.push(s.title)
  lines.push('')
  lines.push(`${s.generatedOn}${new Date().toLocaleString(locale)}`)
  lines.push('')
  lines.push(s.ranking)
  lines.push('')
  ranking.forEach((team, i) => {
    lines.push(`${medals[i] ?? `${i + 1}o`} — ${team.name}: ${team.points} pts`)
  })
  lines.push('')

  ranking.forEach((team) => {
    const teamHistory = history.filter((r) => r.teamId === team.id)
    const correct = teamHistory.filter((r) => r.answeredCorrectly).length
    const wrong = teamHistory.length - correct

    lines.push('---')
    lines.push('')
    lines.push(`## ${team.name}`)
    lines.push('')
    lines.push(`- ${s.finalScore}: ${team.points} pts`)
    lines.push(
      `- ${s.questionsAnswered}: ${teamHistory.length} (${s.correct}: ${correct}, ${s.wrong}: ${wrong})`,
    )
    lines.push('')

    if (teamHistory.length === 0) {
      lines.push(s.noAnswers)
      lines.push('')
      return
    }

    const domains = summarizeDomains(teamHistory).filter((d) => d.total > 0)
    lines.push(s.byDomain)
    lines.push('')
    domains.forEach((d) => {
      lines.push(`- ${d.name} (${d.weight}%): ${d.correct}/${d.total} ${s.correctSuffix}`)
    })
    lines.push('')

    lines.push(s.wrongQuestions)
    lines.push('')
    const wrongQuestions = teamHistory.filter((r) => !r.answeredCorrectly)
    if (wrongQuestions.length === 0) {
      lines.push(s.noneWrong)
    } else {
      wrongQuestions.forEach((r) => {
        lines.push(`- [${r.categoryName} · ${r.points} pts] ${r.prompt}`)
      })
    }
    lines.push('')

    lines.push(s.whatToStudy)
    lines.push('')
    const weak = summarizeDomains(teamHistory)
      .filter((d) => d.total > 0 && d.correct < d.total)
      .sort((a, b) => b.weight - a.weight)

    if (weak.length === 0) {
      lines.push(s.greatJob)
    } else {
      lines.push(s.prioritize)
      lines.push('')
      weak.forEach((d) => {
        lines.push(`**${d.name} (${d.weight}%)**`)
        lines.push(STUDY_TIPS[language][d.category])
        lines.push('')
      })
    }
    lines.push('')

    lines.push(s.claudePromptTitle)
    lines.push('')
    lines.push(s.claudePromptIntro)
    lines.push('')
    buildClaudePrompt(teamHistory, language).forEach((l) => lines.push(l))
    lines.push('')
  })

  lines.push('---')
  lines.push('')
  lines.push(s.footer)
  lines.push('')

  return lines.join('\n')
}

export function extractFailures(history: Result[]) {
  const wrong = history
    .filter((r) => !r.answeredCorrectly)
    .map((r) => ({ category: r.categoryName, prompt: r.prompt }))
  const weak = summarizeDomains(history)
    .filter((d) => d.total > 0 && d.correct < d.total)
    .sort((a, b) => b.weight - a.weight)
    .map((d) => d.name)
  return { wrong, weak }
}

export function downloadReport(fileName: string, content: string) {
  const blob = new Blob([content], { type: 'text/markdown;charset=utf-8' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = fileName
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}

export function downloadPdf(
  fileName: string,
  teams: Team[],
  history: Result[],
  language: Language,
) {
  const doc = new jsPDF({ unit: 'pt', format: 'a4' })
  const margin = 44
  const pageWidth = doc.internal.pageSize.getWidth()
  const pageHeight = doc.internal.pageSize.getHeight()
  const textWidth = pageWidth - margin * 2
  let y = margin

  const md = generateReport(teams, history, language)
  const lines = md.split('\n')

  const write = (text: string, size: number, bold: boolean, color: [number, number, number]) => {
    doc.setFont('helvetica', bold ? 'bold' : 'normal')
    doc.setFontSize(size)
    doc.setTextColor(color[0], color[1], color[2])
    const parts = doc.splitTextToSize(text === '' ? ' ' : text, textWidth)
    for (const part of parts) {
      if (y > pageHeight - margin) {
        doc.addPage()
        y = margin
      }
      doc.text(part, margin, y)
      y += size + 4
    }
  }

  for (const line of lines) {
    const clean = line.replace(/`/g, '').replace(/\*\*/g, '').replace(/_/g, '')
    if (line.startsWith('# ')) write(clean.slice(2), 18, true, [20, 20, 20])
    else if (line.startsWith('## ')) write(clean.slice(3), 14, true, [40, 40, 40])
    else if (line.startsWith('### ')) write(clean.slice(4), 12, true, [60, 60, 60])
    else if (line === '---') {
      y += 4
    } else write(clean, 10, false, [30, 30, 30])
  }

  doc.save(fileName)
}
